// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type User struct {
	ID        int32
	JiraID    string
	Username  string
	CreatedAt time.Time
	LastLogin time.Time
}

type UserSetting struct {
	UserID             int32
	ProjectID          string
	IssueQuery         string
	ContentTemplate    string
	TicketItemTemplate string
	MailRecipient      string
	MailSubject        string
	MailAuthor         string
	UpdatedAt          time.Time
}
