// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (jira_id, username)
values ($1, $2)
returning id, jira_id, username, created_at, last_login
`

type CreateUserParams struct {
	JiraID   string
	Username string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.JiraID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.JiraID,
		&i.Username,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getUserByJiraID = `-- name: GetUserByJiraID :one
SELECT id, jira_id, username, created_at, last_login
FROM users
WHERE jira_id = $1
`

func (q *Queries) GetUserByJiraID(ctx context.Context, jiraID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByJiraID, jiraID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.JiraID,
		&i.Username,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
update users
SET last_login = now()
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, updateLastLogin, id)
	return err
}
