// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_settings.sql

package db

import (
	"context"
)

const getSettingsByUserID = `-- name: GetSettingsByUserID :one
SELECT user_id, project_id, issue_query, content_template, ticket_item_template, mail_recipient, mail_subject, mail_author, updated_at
FROM user_settings
WHERE user_id = $1
`

func (q *Queries) GetSettingsByUserID(ctx context.Context, userID int32) (UserSetting, error) {
	row := q.db.QueryRowContext(ctx, getSettingsByUserID, userID)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.ProjectID,
		&i.IssueQuery,
		&i.ContentTemplate,
		&i.TicketItemTemplate,
		&i.MailRecipient,
		&i.MailSubject,
		&i.MailAuthor,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSettings = `-- name: UpsertSettings :exec
INSERT INTO user_settings (
        user_id,
        project_id,
        issue_query,
        content_template,
        ticket_item_template,
        mail_recipient,
        mail_subject,
        mail_author
    )
values ($1, $2, $3, $4, $5, $6, $7, $8) ON conflict (user_id) do
update
SET project_id = excluded.project_id,
    issue_query = excluded.issue_query,
    content_template = excluded.content_template,
    ticket_item_template = excluded.ticket_item_template,
    mail_recipient = excluded.mail_recipient,
    mail_subject = excluded.mail_subject,
    mail_author = excluded.mail_author,
    updated_at = now()
`

type UpsertSettingsParams struct {
	UserID             int32
	ProjectID          string
	IssueQuery         string
	ContentTemplate    string
	TicketItemTemplate string
	MailRecipient      string
	MailSubject        string
	MailAuthor         string
}

func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertSettings,
		arg.UserID,
		arg.ProjectID,
		arg.IssueQuery,
		arg.ContentTemplate,
		arg.TicketItemTemplate,
		arg.MailRecipient,
		arg.MailSubject,
		arg.MailAuthor,
	)
	return err
}
